[package]
name = "playground-rocket"
version = "0.1.0"
authors = ["Stefan Weisser <stefan.weisser@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "1.4.3", features = ["sqlite", "r2d2"] }
dotenv = "0.15.0"
prometheus = "0.7"
rocket_prometheus = "0.3.2"
once_cell = "1.3.1"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["diesel_sqlite_pool", "json"]
